### ISSUE TITLE
Make sure Miao is based on corrected Unicode glyphs

### ISSUE THREAD

**Issue by roozbehp** [notofonts/miao#1]
Unicode has published an erratum on Miao glyphs at http://unicode.org/errata/ (search for 2016-01-15):

> Glyphs for the characters U+16F2C - U+16F32 are incorrect in the chart for the Miao script, in Unicode 8.0. The image below shows the incorrect glyph cells on the left, and the correct glyph cells on the right.

![](http://unicode.org/errata/miao-glyph-erratum-16f2c-16f32.jpg)

Please make sure that the new Miao font uses the corrected glyphs.

**Comment by simoncozens** [comment]
Android currently has version 2.000 of Noto Sans Miao. I have recommended an upgrade of this font for the next API release. I'm sorry, but it means having to wait again, but it will get fixed.

**Comment by cheuk879** [comment]
When is the next API release?

**Comment by simoncozens** [comment]
Sorry I didn't get back to you about this. But current Android appears to have Noto Sans Miao 2.001 (which has the correct glyphs), so I think we are good now.
