### ISSUE TITLE
Alternate Glyphs for Lipo [lpo]

### ISSUE THREAD

**Issue by cheuk879** [notofonts/miao#2]
### Title 
  Alternate Glyphs for Lipo [lpo]

### Font 
  NotoSansMiao-Regular.ttf

### Where the font came from, and when
  Site: https://github.com/googlefonts/noto-fonts/raw/master/hinted/ttf/NotoSansMiao/NotoSansMiao-Regular.ttf
  Date: 2021-03-01

### Font Version
  2.001

### OS name and version
  Windows 10 Pro (Versions 2004 & 20H2)

### Application name and version
  LibreOffice Writer & Calc 7.0.4.2 (x64)

### Issue
  Lipo [lpo] is 1 of 7 known languages that use the Miao script.  Glyphs for select characters are different from the other languages, but currently NotoSansMiao is rendering them the same for all.  Language-specific behaviour is needed for Lipo as in the Taogu font of the Shimenkan font package.
  
  1. Steps to reproduce:
     - Download & install Taogu at https://software.sil.org/downloads/r/shimenkan/Taogu-1.000.zip
     - Unzip the attached archive: [plrd-noto-bug-lpoglyphs.zip](https://github.com/googlefonts/noto-fonts/files/6224662/plrd-noto-bug-lpoglyphs.zip)
     - Open the ODS document "plrd-noto-bug-lpoglyphs.ods"
  2. Observed results:		See column B (NotoSansMiao)
  3. Expected results:		See column C (Taogu)
  4. Additional information:	See column D
     - For convenience, a corresponding PDF document is also included in the archive.
     - For comparison, language-specific fonts for the other languages using the Miao script are available at https://software.sil.org/shimenkan/

**Comment by simoncozens** [comment]
Thanks to Paul, we now have alternate forms for Lipo!

```
$ shape fonts/NotoSansMiao/unhinted/ttf/NotoSansMiao-Regular.ttf -u 16f04,16f10
[u16F04=0+580|u16F10=1+580]
```
![shape](https://github.com/user-attachments/assets/7f0f1acb-6ba6-4fcd-8d82-58ef9cbc732e)

```
$ shape fonts/NotoSansMiao/unhinted/ttf/NotoSansMiao-Regular.ttf -u 16f04,16f10 --language=lpo
[u16F04.lpo=0+637|u16F10.lpo=1+637]
```
![shape](https://github.com/user-attachments/assets/23366736-3a3f-4739-9abd-607fecc37c60)
